name: StealthLogin

main: net.craftrepo.StealthLogin.StealthLogin

version: 1.2.0

commands:
    logincheck:
        description: Check which online players have permissions for Logins
        usage: |
               /<command>
    kickcheck:
        description: Check which online players have permissions for Kicks
        usage: |
               /<command>
    loginshow:
        description: Show a fake login message
        usage: |
               /<command>
    logoutshow:    
        description: Show a fake logout message       
        usage: |
               /<command>
    listplayers:    
        description: Lists players currently online
        aliases: ['list','who']       
        usage: |
               /<command>
 