name: StealthLogin

main: net.craftrepo.StealthLogin.StealthLogin

version: 1.0.0

commands:
    logincheck:
        description: Check which online players have permissions for Logins
        usage: |
               /<command>
    kickcheck:
        description: Check which online players have permissions for Logouts
        usage: |
               /<command>